/// Flutter icons CalculatorIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CalculatorIcons
///      fonts:
///       - asset: fonts/CalculatorIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class CalculatorIcons {
  CalculatorIcons._();

  static const _kFontFam = 'CalculatorIcons';
  static const String? _kFontPkg = null;

  static const IconData plus =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calc =
      IconData(0xf1ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData divide =
      IconData(0xf529, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equals =
      IconData(0xf52c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percentage =
      IconData(0xf541, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backspace =
      IconData(0xf55a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
